#!/bin/bash

FORMAT_COMMAND="clang-format -i"

function FORMAT_FILTER {
    egrep '\.(c|cpp|cc|h|hpp|hh)$' "$1"
}

for file in $(git diff-index --cached --name-only HEAD) ; do
    if [ -n "$(FORMAT_FILTER $file)" ]
    then
        tmp=$(mktemp)
        mv "$file" "$tmp"
        git show :"$file" > "$file"
        "$FORMAT_COMMAND" "$file"
        git add "$file"
        mv "$tmp" "$file"
    fi
done
